# Generated by Django 4.2.1 on 2024-05-17 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
